[package]
name = "anthos-app"
version = "0.1.0"
description = "Anthos plant monitoring app"
authors = ["Anthos Team"]
edition = "2021"

[lib]
name = "anthos_app_lib"
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-blec = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
